Disable device farm

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -347,72 +347,72 @@ jobs:
           aws-region: us-west-2
 
       # io.realm.testapp and io.realm.sync.testapp
-      - name: Run the tests
-        uses: realm/aws-devicefarm/test-application@d94e739490340474f8464f74289a0f48706dd3a3
-        id: run_tests
-        with:
-          project_arn: ${{ secrets.DEVICEFARM_PROJECT_ARN }}
-          device_pool_arn: ${{ secrets.DEVICEFARM_ANDROID_POOL_ARN }}
-          app_file: ${{ github.workspace }}/test/build/intermediates/apk/androidTest/debug/base-debug-androidTest.apk
-          app_type: ANDROID_APP
-          test_type: APPIUM_PYTHON
-          test_package_file: https://github.com/realm/aws-devicefarm-sample-data/releases/download/0.3/sample_env_python3.zip
-          test_package_type: APPIUM_PYTHON_TEST_PACKAGE
-          test_spec_file: test_spec.yaml
-          test_spec_type: APPIUM_PYTHON_TEST_SPEC
-          remote_src: true
-          test_spec: |
-            version: 0.1
-            phases:
-              install:
-                commands:
-                  - export PYTHON_VERSION=3
-              pre_test:
-                commands:
-                  - adb -s $DEVICEFARM_DEVICE_UDID shell pm grant io.realm.testapp android.permission.READ_EXTERNAL_STORAGE
-                  - adb -s $DEVICEFARM_DEVICE_UDID shell pm grant io.realm.testapp android.permission.WRITE_EXTERNAL_STORAGE
-              test:
-                commands:
-                  - echo " --baasurl=${{ secrets.BaseUrl }} --baascluster=${{ inputs.clusterName }} --baasapikey=${{ secrets.AtlasPublicKey}} --baasprivateapikey=${{ secrets.AtlasPrivateKey}} --baasprojectid=${{ secrets.AtlasProjectId }} --baasdifferentiator=xamarinandroid" > testargs.txt
-                  - adb -s $DEVICEFARM_DEVICE_UDID push testargs.txt /storage/emulated/0/RealmTests/testargs.txt
-                  - adb -s $DEVICEFARM_DEVICE_UDID shell am instrument -w -r io.realm.xamarintests/.TestRunner
-              post_test:
-                commands:
-                  - adb -s $DEVICEFARM_DEVICE_UDID pull /storage/emulated/0/RealmTests/TestResults.Android.xml $DEVICEFARM_LOG_DIR/TestResults.Android.xml
-            artifacts:
-              - $DEVICEFARM_LOG_DIR
-          file_artifacts: |
-            Customer Artifacts.zip
+      # - name: Run the tests
+      #   uses: realm/aws-devicefarm/test-application@d94e739490340474f8464f74289a0f48706dd3a3
+      #   id: run_tests
+      #   with:
+      #     project_arn: ${{ secrets.DEVICEFARM_PROJECT_ARN }}
+      #     device_pool_arn: ${{ secrets.DEVICEFARM_ANDROID_POOL_ARN }}
+      #     app_file: ${{ github.workspace }}/test/build/intermediates/apk/androidTest/debug/base-debug-androidTest.apk
+      #     app_type: ANDROID_APP
+      #     test_type: APPIUM_PYTHON
+      #     test_package_file: https://github.com/realm/aws-devicefarm-sample-data/releases/download/0.3/sample_env_python3.zip
+      #     test_package_type: APPIUM_PYTHON_TEST_PACKAGE
+      #     test_spec_file: test_spec.yaml
+      #     test_spec_type: APPIUM_PYTHON_TEST_SPEC
+      #     remote_src: true
+      #     test_spec: |
+      #       version: 0.1
+      #       phases:
+      #         install:
+      #           commands:
+      #             - export PYTHON_VERSION=3
+      #         pre_test:
+      #           commands:
+      #             - adb -s $DEVICEFARM_DEVICE_UDID shell pm grant io.realm.testapp android.permission.READ_EXTERNAL_STORAGE
+      #             - adb -s $DEVICEFARM_DEVICE_UDID shell pm grant io.realm.testapp android.permission.WRITE_EXTERNAL_STORAGE
+      #         test:
+      #           commands:
+      #             - echo " --baasurl=${{ secrets.BaseUrl }} --baascluster=${{ inputs.clusterName }} --baasapikey=${{ secrets.AtlasPublicKey}} --baasprivateapikey=${{ secrets.AtlasPrivateKey}} --baasprojectid=${{ secrets.AtlasProjectId }} --baasdifferentiator=xamarinandroid" > testargs.txt
+      #             - adb -s $DEVICEFARM_DEVICE_UDID push testargs.txt /storage/emulated/0/RealmTests/testargs.txt
+      #             - adb -s $DEVICEFARM_DEVICE_UDID shell am instrument -w -r io.realm.xamarintests/.TestRunner
+      #         post_test:
+      #           commands:
+      #             - adb -s $DEVICEFARM_DEVICE_UDID pull /storage/emulated/0/RealmTests/TestResults.Android.xml $DEVICEFARM_LOG_DIR/TestResults.Android.xml
+      #       artifacts:
+      #         - $DEVICEFARM_LOG_DIR
+      #     file_artifacts: |
+      #       Customer Artifacts.zip
 
-      - name: Fetch test artifacts
-        run: |
-          Expand-Archive 'Customer Artifacts.zip' -DestinationPath artifacts
-          Import-Module AWSPowerShell
-          $jobs = Get-DFJobList -Arn ${{ steps.run_tests.outputs.arn }}
-          $suites = Get-DFSuiteList -Arn $jobs[0].Arn
-          $artifacts = Get-DFArtifactList -Arn $suites[1].Arn -Type File | Where-Object { $_.Name -EQ "Logcat" }
-          echo "::group::Logcat"
-          Invoke-WebRequest -Uri $artifacts[0].Url | Select-Object -Expand RawContent
-          echo "::endgroup::"
+      # - name: Fetch test artifacts
+      #   run: |
+      #     Expand-Archive 'Customer Artifacts.zip' -DestinationPath artifacts
+      #     Import-Module AWSPowerShell
+      #     $jobs = Get-DFJobList -Arn ${{ steps.run_tests.outputs.arn }}
+      #     $suites = Get-DFSuiteList -Arn $jobs[0].Arn
+      #     $artifacts = Get-DFArtifactList -Arn $suites[1].Arn -Type File | Where-Object { $_.Name -EQ "Logcat" }
+      #     echo "::group::Logcat"
+      #     Invoke-WebRequest -Uri $artifacts[0].Url | Select-Object -Expand RawContent
+      #     echo "::endgroup::"
 
-      - name: Device Farm Raw JSON Output
-        run: |
-          echo "::group::Data"
-          echo (ConvertFrom-Json '${{ steps.run_tests.outputs.data }}' | ConvertTo-Json)
-          echo "::endgroup::"
-        if: always()
+      # - name: Device Farm Raw JSON Output
+      #   run: |
+      #     echo "::group::Data"
+      #     echo (ConvertFrom-Json '${{ steps.run_tests.outputs.data }}' | ConvertTo-Json)
+      #     echo "::endgroup::"
+      #   if: always()
 
-      - name: Publish Unit Test Results
-        uses: dorny/test-reporter@v1
-        if: always() || failure()
-        with:
-          name: Results - Android Base (Device Farm)
-          path: ./test/base/build/**/TEST-*.xml
-          reporter: java-junit
-          list-suites: failed
-          list-tests: failed
-          # path-replace-backslashes: true
-          fail-on-error: true
+      # - name: Publish Unit Test Results
+      #   uses: dorny/test-reporter@v1
+      #   if: always() || failure()
+      #   with:
+      #     name: Results - Android Base (Device Farm)
+      #     path: ./test/base/build/**/TEST-*.xml
+      #     reporter: java-junit
+      #     list-suites: failed
+      #     list-tests: failed
+      #     # path-replace-backslashes: true
+      #     fail-on-error: true
 
 
   test-macos-packages:
